/**
 * Connector catalog — the SPA half of the source of truth.
 *
 * Every entry here must have a matching entry in apps/api/src/lib/providerRegistry.ts
 * (endpoints, scopes, env vars) and a brand mark in public/integrations/<id>.svg.
 * `npm run check:connectors` fails CI when the three drift apart.
 *
 * Icons are Iconify names resolved at build time by scripts/gen/provider-icons.mjs.
 * Read-only everywhere: Company OS never requests a send, write, or delete scope
 * (docs/design/09_CONNECTORS.md §9.2).
 */

export const PROVIDER_IDS = [
  // Email
  "gmail",
  "outlook",
  "front",
  // Calendar
  "google_calendar",
  "microsoft_calendar",
  "calendly",
  // Meetings
  "zoom",
  "google_meet",
  "webex",
  "fathom",
  "gong",
  "loom",
  // Messaging
  "slack",
  "teams",
  "google_chat",
  "discord",
  "telegram",
  "whatsapp",
  "twilio",
  // Project tracking
  "jira",
  "asana",
  "linear",
  "monday",
  "clickup",
  "trello",
  "basecamp",
  "todoist",
  "shortcut",
  // Docs & knowledge
  "notion",
  "confluence",
  "google_docs",
  "google_sheets",
  "coda",
  "airtable",
  // Storage
  "google_drive",
  "onedrive",
  "sharepoint",
  "dropbox",
  "box",
  // CRM & sales
  "hubspot",
  "salesforce",
  "pipedrive",
  "zoho_crm",
  "docusign",
  // Support
  "zendesk",
  "intercom",
  "helpscout",
  // Engineering
  "github",
  "gitlab",
  "bitbucket",
  "sentry",
  "pagerduty",
  "datadog",
  // Design
  "figma",
  "miro",
  // People
  "greenhouse",
  "gusto",
  "personio",
  // Finance
  "stripe",
  "quickbooks",
  "xero",
  "shopify",
  // Marketing & forms
  "mailchimp",
  "sendgrid",
  "typeform",
  "google_forms",
  // Analytics
  "google_analytics",
  "mixpanel",
  "amplitude",
  "segment",
  // Identity
  "okta",
  "auth0",
  "workos",
  // Automation
  "zapier",
  "make",
  "n8n",
] as const;

export type ConnectionProvider = (typeof PROVIDER_IDS)[number];

export const PROVIDER_CATEGORIES = [
  "Email",
  "Calendar",
  "Meetings",
  "Messaging",
  "Project tracking",
  "Docs & knowledge",
  "Storage",
  "CRM & sales",
  "Support",
  "Engineering",
  "Design",
  "People",
  "Finance",
  "Marketing & forms",
  "Analytics",
  "Identity",
  "Automation",
] as const;

export type ProviderCategory = (typeof PROVIDER_CATEGORIES)[number];

/**
 * How an admin proves the workspace owns the account.
 *  oauth2  — redirect handshake, PKCE, refresh tokens (preferred)
 *  api_key — provider-issued read token pasted once, encrypted at rest
 *  webhook — provider pushes to a per-tenant signed endpoint; nothing to poll
 */
export type ProviderAuth = "oauth2" | "api_key" | "webhook";

export interface ProviderMeta {
  id: ConnectionProvider;
  name: string;
  category: ProviderCategory;
  auth: ProviderAuth;
  /** Org-level connections are shared by the workspace; others are per person. */
  orgLevel?: boolean;
  /** What Company OS reads. Plain language — this string is shown to users. */
  reads: string;
  /** Read-only scopes or permissions requested. */
  scopesNote: string;
  /** Iconify name for the brand mark. */
  icon: string;
  /** Provider-side setup docs for whoever creates the credentials. */
  docsUrl: string;
  /** Offered during onboarding; the rest live on /integrations. */
  core?: boolean;
}

export const PROVIDERS: ProviderMeta[] = [
  // ── Email ────────────────────────────────────────────────────────────────
  {
    id: "gmail",
    name: "Gmail",
    category: "Email",
    auth: "oauth2",
    reads: "Thread headers and bodies you can already see, for commitments made over email.",
    scopesNote: "gmail.readonly",
    icon: "logos:google-gmail",
    docsUrl: "https://developers.google.com/gmail/api/auth/scopes",
    core: true,
  },
  {
    id: "outlook",
    name: "Outlook",
    category: "Email",
    auth: "oauth2",
    reads: "Mail you can already see, for commitments made over email.",
    scopesNote: "Mail.Read",
    icon: "thesvg-color:microsoft-outlook",
    docsUrl: "https://learn.microsoft.com/graph/permissions-reference",
  },
  {
    id: "front",
    name: "Front",
    category: "Email",
    auth: "oauth2",
    orgLevel: true,
    reads: "Shared inbox conversations and assignees.",
    scopesNote: "read",
    icon: "thesvg-color:front",
    docsUrl: "https://dev.frontapp.com/docs/oauth",
  },

  // ── Calendar ─────────────────────────────────────────────────────────────
  {
    id: "google_calendar",
    name: "Google Calendar",
    category: "Calendar",
    auth: "oauth2",
    reads: "Events, attendees and recurrence so meetings can be matched to their follow-through.",
    scopesNote: "calendar.readonly",
    icon: "logos:google-calendar",
    docsUrl: "https://developers.google.com/calendar/api/auth",
    core: true,
  },
  {
    id: "microsoft_calendar",
    name: "Microsoft Calendar",
    category: "Calendar",
    auth: "oauth2",
    reads: "Events and attendees from Microsoft 365.",
    scopesNote: "Calendars.Read, User.Read",
    icon: "thesvg-color:outlook-calendar",
    docsUrl: "https://learn.microsoft.com/graph/permissions-reference",
    core: true,
  },
  {
    id: "calendly",
    name: "Calendly",
    category: "Calendar",
    auth: "oauth2",
    reads: "Scheduled events and invitees.",
    scopesNote: "default (read)",
    icon: "thesvg-color:calendly",
    docsUrl: "https://developer.calendly.com/api-docs",
  },

  // ── Meetings ─────────────────────────────────────────────────────────────
  {
    id: "zoom",
    name: "Zoom",
    category: "Meetings",
    auth: "oauth2",
    reads: "Cloud transcript text and participants. Audio is never downloaded or stored.",
    scopesNote: "meeting:read, recording:read",
    icon: "logos:zoom-icon",
    docsUrl: "https://developers.zoom.us/docs/integrations/oauth/",
    core: true,
  },
  {
    id: "google_meet",
    name: "Google Meet",
    category: "Meetings",
    auth: "oauth2",
    reads: "Meeting spaces, participants and transcript text.",
    scopesNote: "meetings.space.readonly",
    icon: "thesvg-color:google-meet",
    docsUrl: "https://developers.google.com/meet/api/guides/overview",
  },
  {
    id: "webex",
    name: "Webex",
    category: "Meetings",
    auth: "oauth2",
    reads: "Meeting details, participants and transcript text.",
    scopesNote: "meeting:schedules_read, meeting:recordings_read",
    icon: "thesvg-color:webex",
    docsUrl: "https://developer.webex.com/docs/integrations",
  },
  {
    id: "fathom",
    name: "Fathom",
    category: "Meetings",
    auth: "webhook",
    orgLevel: true,
    reads: "Meeting transcripts and participants, pushed to a per-workspace signed endpoint.",
    scopesNote: "recordings.read (transcript text only)",
    icon: "",
    docsUrl: "https://docs.fathom.video/",
    core: true,
  },
  {
    id: "gong",
    name: "Gong",
    category: "Meetings",
    auth: "api_key",
    orgLevel: true,
    reads: "Call transcripts and participants for revenue conversations.",
    scopesNote: "api:calls:read:basic, api:calls:read:transcript",
    icon: "thesvg-color:gong",
    docsUrl: "https://gong.app.gong.io/settings/api/documentation",
  },
  {
    id: "loom",
    name: "Loom",
    category: "Meetings",
    auth: "api_key",
    orgLevel: true,
    reads: "Video titles, descriptions and transcript text.",
    scopesNote: "read-only workspace token",
    icon: "logos:loom-icon",
    docsUrl: "https://dev.loom.com/docs/public-api",
  },

  // ── Messaging ────────────────────────────────────────────────────────────
  {
    id: "slack",
    name: "Slack",
    category: "Messaging",
    auth: "oauth2",
    orgLevel: true,
    reads: "History of allowlisted channels only. Direct messages are never read.",
    scopesNote: "channels:history, channels:read, users:read",
    icon: "logos:slack-icon",
    docsUrl: "https://api.slack.com/authentication/oauth-v2",
    core: true,
  },
  {
    id: "teams",
    name: "Microsoft Teams",
    category: "Messaging",
    auth: "oauth2",
    orgLevel: true,
    reads: "Allowlisted channel messages. Private chats are never read.",
    scopesNote: "ChannelMessage.Read.All",
    icon: "logos:microsoft-teams",
    docsUrl: "https://learn.microsoft.com/graph/permissions-reference",
  },
  {
    id: "google_chat",
    name: "Google Chat",
    category: "Messaging",
    auth: "oauth2",
    orgLevel: true,
    reads: "Allowlisted space messages.",
    scopesNote: "chat.spaces.readonly, chat.messages.readonly",
    icon: "thesvg-color:google-chat",
    docsUrl: "https://developers.google.com/chat/api/guides/auth",
  },
  {
    id: "discord",
    name: "Discord",
    category: "Messaging",
    auth: "oauth2",
    orgLevel: true,
    reads: "Allowlisted server channel messages.",
    scopesNote: "identify, guilds, messages.read",
    icon: "logos:discord-icon",
    docsUrl: "https://discord.com/developers/docs/topics/oauth2",
  },
  {
    id: "telegram",
    name: "Telegram",
    category: "Messaging",
    auth: "api_key",
    orgLevel: true,
    reads: "Check-in replies from the workspace bot. Company OS also sends here.",
    scopesNote: "bot token (send + receive check-ins)",
    icon: "logos:telegram",
    docsUrl: "https://core.telegram.org/bots/api",
    core: true,
  },
  {
    id: "whatsapp",
    name: "WhatsApp",
    category: "Messaging",
    auth: "api_key",
    orgLevel: true,
    reads: "Check-in replies on the workspace number. Company OS also sends here.",
    scopesNote: "Cloud API phone number + app secret",
    icon: "logos:whatsapp-icon",
    docsUrl: "https://developers.facebook.com/docs/whatsapp/cloud-api",
  },
  {
    id: "twilio",
    name: "Twilio",
    category: "Messaging",
    auth: "api_key",
    orgLevel: true,
    reads: "Delivery status for WhatsApp and SMS check-ins.",
    scopesNote: "Account SID + auth token",
    icon: "logos:twilio-icon",
    docsUrl: "https://www.twilio.com/docs/usage/api",
  },

  // ── Project tracking ─────────────────────────────────────────────────────
  {
    id: "jira",
    name: "Jira",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "Issues, assignees and due dates, so tracked work is not duplicated.",
    scopesNote: "read:jira-work, read:jira-user",
    icon: "logos:jira",
    docsUrl: "https://developer.atlassian.com/cloud/jira/platform/oauth-2-3lo-apps/",
    core: true,
  },
  {
    id: "asana",
    name: "Asana",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "Tasks, assignees and due dates.",
    scopesNote: "tasks:read, projects:read, users:read",
    icon: "logos:asana-icon",
    docsUrl: "https://developers.asana.com/docs/oauth",
  },
  {
    id: "linear",
    name: "Linear",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "Issues, assignees, cycles and due dates.",
    scopesNote: "read",
    icon: "thesvg-color:linear",
    docsUrl: "https://developers.linear.app/docs/oauth/authentication",
  },
  {
    id: "monday",
    name: "monday.com",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "Board items, owners and timeline columns.",
    scopesNote: "boards:read, users:read",
    icon: "logos:monday-icon",
    docsUrl: "https://developer.monday.com/apps/docs/oauth",
  },
  {
    id: "clickup",
    name: "ClickUp",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "Tasks, assignees and due dates.",
    scopesNote: "read-only app token",
    icon: "logos:clickup-icon",
    docsUrl: "https://developer.clickup.com/docs/authentication",
  },
  {
    id: "trello",
    name: "Trello",
    category: "Project tracking",
    auth: "api_key",
    orgLevel: true,
    reads: "Cards, members and due dates.",
    scopesNote: "API key + read token",
    icon: "logos:trello",
    docsUrl: "https://developer.atlassian.com/cloud/trello/guides/rest-api/api-introduction/",
  },
  {
    id: "basecamp",
    name: "Basecamp",
    category: "Project tracking",
    auth: "oauth2",
    orgLevel: true,
    reads: "To-dos, assignees and due dates.",
    scopesNote: "read-only account access",
    icon: "logos:basecamp-icon",
    docsUrl: "https://github.com/basecamp/api/blob/master/sections/authentication.md",
  },
  {
    id: "todoist",
    name: "Todoist",
    category: "Project tracking",
    auth: "oauth2",
    reads: "Tasks, projects and due dates.",
    scopesNote: "data:read",
    icon: "logos:todoist-icon",
    docsUrl: "https://developer.todoist.com/guides/#authorization",
  },
  {
    id: "shortcut",
    name: "Shortcut",
    category: "Project tracking",
    auth: "api_key",
    orgLevel: true,
    reads: "Stories, owners and deadlines.",
    scopesNote: "read-only API token",
    icon: "logos:shortcut-icon",
    docsUrl: "https://developer.shortcut.com/api/rest/v3",
  },

  // ── Docs & knowledge ─────────────────────────────────────────────────────
  {
    id: "notion",
    name: "Notion",
    category: "Docs & knowledge",
    auth: "oauth2",
    orgLevel: true,
    reads: "Pages and databases shared with the integration.",
    scopesNote: "read content (per-page grant)",
    icon: "logos:notion-icon",
    docsUrl: "https://developers.notion.com/docs/authorization",
    core: true,
  },
  {
    id: "confluence",
    name: "Confluence",
    category: "Docs & knowledge",
    auth: "oauth2",
    orgLevel: true,
    reads: "Page content and comments in allowlisted spaces.",
    scopesNote: "read:confluence-content.summary",
    icon: "logos:confluence",
    docsUrl: "https://developer.atlassian.com/cloud/confluence/oauth-2-3lo-apps/",
  },
  {
    id: "google_docs",
    name: "Google Docs",
    category: "Docs & knowledge",
    auth: "oauth2",
    reads: "Document text for docs already shared with you.",
    scopesNote: "documents.readonly",
    icon: "thesvg-color:google-docs",
    docsUrl: "https://developers.google.com/docs/api/how-tos/authorizing",
  },
  {
    id: "google_sheets",
    name: "Google Sheets",
    category: "Docs & knowledge",
    auth: "oauth2",
    reads: "Sheet values for trackers you point Company OS at.",
    scopesNote: "spreadsheets.readonly",
    icon: "thesvg-color:google-sheets",
    docsUrl: "https://developers.google.com/sheets/api/scopes",
  },
  {
    id: "coda",
    name: "Coda",
    category: "Docs & knowledge",
    auth: "api_key",
    orgLevel: true,
    reads: "Doc tables and rows.",
    scopesNote: "read-only API token",
    icon: "logos:coda-icon",
    docsUrl: "https://coda.io/developers/apis/v1",
  },
  {
    id: "airtable",
    name: "Airtable",
    category: "Docs & knowledge",
    auth: "oauth2",
    orgLevel: true,
    reads: "Base records in tables you grant.",
    scopesNote: "data.records:read, schema.bases:read",
    icon: "logos:airtable",
    docsUrl: "https://airtable.com/developers/web/guides/oauth-integrations",
  },

  // ── Storage ──────────────────────────────────────────────────────────────
  {
    id: "google_drive",
    name: "Google Drive",
    category: "Storage",
    auth: "oauth2",
    reads: "File metadata only — names, owners and edit times. Never file content.",
    scopesNote: "drive.metadata.readonly",
    icon: "logos:google-drive",
    docsUrl: "https://developers.google.com/drive/api/guides/api-specific-auth",
  },
  {
    id: "onedrive",
    name: "OneDrive",
    category: "Storage",
    auth: "oauth2",
    reads: "File metadata only — names, owners and edit times.",
    scopesNote: "Files.Read.All",
    icon: "logos:microsoft-onedrive",
    docsUrl: "https://learn.microsoft.com/graph/permissions-reference",
  },
  {
    id: "sharepoint",
    name: "SharePoint",
    category: "Storage",
    auth: "oauth2",
    orgLevel: true,
    reads: "Site and document library metadata.",
    scopesNote: "Sites.Read.All",
    icon: "thesvg-color:microsoft-sharepoint",
    docsUrl: "https://learn.microsoft.com/graph/permissions-reference",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    category: "Storage",
    auth: "oauth2",
    reads: "File metadata only — names, owners and edit times.",
    scopesNote: "files.metadata.read",
    icon: "logos:dropbox",
    docsUrl: "https://developers.dropbox.com/oauth-guide",
  },
  {
    id: "box",
    name: "Box",
    category: "Storage",
    auth: "oauth2",
    reads: "File metadata only — names, owners and edit times.",
    scopesNote: "root_readonly",
    icon: "logos:box",
    docsUrl: "https://developer.box.com/guides/authentication/oauth2/",
  },

  // ── CRM & sales ──────────────────────────────────────────────────────────
  {
    id: "hubspot",
    name: "HubSpot",
    category: "CRM & sales",
    auth: "oauth2",
    orgLevel: true,
    reads: "Deals, companies, owners and logged activity.",
    scopesNote: "crm.objects.deals.read, crm.objects.contacts.read",
    icon: "thesvg-color:hubspot",
    docsUrl: "https://developers.hubspot.com/docs/api/oauth-quickstart-guide",
    core: true,
  },
  {
    id: "salesforce",
    name: "Salesforce",
    category: "CRM & sales",
    auth: "oauth2",
    orgLevel: true,
    reads: "Opportunities, accounts, owners and tasks.",
    scopesNote: "api, refresh_token (read-only profile)",
    icon: "logos:salesforce",
    docsUrl: "https://help.salesforce.com/s/articleView?id=sf.connected_app_create.htm",
  },
  {
    id: "pipedrive",
    name: "Pipedrive",
    category: "CRM & sales",
    auth: "oauth2",
    orgLevel: true,
    reads: "Deals, activities and owners.",
    scopesNote: "deals:read, activities:read, users:read",
    icon: "thesvg-color:pipedrive",
    docsUrl: "https://pipedrive.readme.io/docs/marketplace-oauth-authorization",
  },
  {
    id: "zoho_crm",
    name: "Zoho CRM",
    category: "CRM & sales",
    auth: "oauth2",
    orgLevel: true,
    reads: "Deals, accounts and owners.",
    scopesNote: "ZohoCRM.modules.READ",
    icon: "logos:zoho",
    docsUrl: "https://www.zoho.com/crm/developer/docs/api/v6/oauth-overview.html",
  },
  {
    id: "docusign",
    name: "DocuSign",
    category: "CRM & sales",
    auth: "oauth2",
    orgLevel: true,
    reads: "Envelope status and signers — who still owes a signature.",
    scopesNote: "signature (read), impersonation off",
    icon: "thesvg-color:docusign",
    docsUrl: "https://developers.docusign.com/platform/auth/authcode/",
  },

  // ── Support ──────────────────────────────────────────────────────────────
  {
    id: "zendesk",
    name: "Zendesk",
    category: "Support",
    auth: "oauth2",
    orgLevel: true,
    reads: "Tickets, assignees and due dates.",
    scopesNote: "read",
    icon: "logos:zendesk-icon",
    docsUrl: "https://developer.zendesk.com/documentation/ticketing/working-with-oauth/",
  },
  {
    id: "intercom",
    name: "Intercom",
    category: "Support",
    auth: "oauth2",
    orgLevel: true,
    reads: "Conversations, assignees and customer follow-ups.",
    scopesNote: "read conversations, read admins",
    icon: "logos:intercom-icon",
    docsUrl: "https://developers.intercom.com/docs/build-an-integration/learn-more/authentication/",
  },
  {
    id: "helpscout",
    name: "Help Scout",
    category: "Support",
    auth: "oauth2",
    orgLevel: true,
    reads: "Conversations and assignees.",
    scopesNote: "read",
    icon: "logos:helpscout-icon",
    docsUrl: "https://developer.helpscout.com/mailbox-api/overview/authentication/",
  },

  // ── Engineering ──────────────────────────────────────────────────────────
  {
    id: "github",
    name: "GitHub",
    category: "Engineering",
    auth: "oauth2",
    orgLevel: true,
    reads: "Issues, pull requests, reviewers and review requests.",
    scopesNote: "read:org, repo:status, read:user",
    icon: "logos:github-icon",
    docsUrl: "https://docs.github.com/apps/oauth-apps/building-oauth-apps",
    core: true,
  },
  {
    id: "gitlab",
    name: "GitLab",
    category: "Engineering",
    auth: "oauth2",
    orgLevel: true,
    reads: "Issues, merge requests and reviewers.",
    scopesNote: "read_api, read_user",
    icon: "logos:gitlab-icon",
    docsUrl: "https://docs.gitlab.com/ee/api/oauth2.html",
  },
  {
    id: "bitbucket",
    name: "Bitbucket",
    category: "Engineering",
    auth: "oauth2",
    orgLevel: true,
    reads: "Pull requests and reviewers.",
    scopesNote: "repository, pullrequest (read)",
    icon: "logos:bitbucket",
    docsUrl: "https://developer.atlassian.com/cloud/bitbucket/oauth-2/",
  },
  {
    id: "sentry",
    name: "Sentry",
    category: "Engineering",
    auth: "api_key",
    orgLevel: true,
    reads: "Unresolved issues and their assignees.",
    scopesNote: "org:read, project:read, event:read",
    icon: "logos:sentry-icon",
    docsUrl: "https://docs.sentry.io/api/auth/",
  },
  {
    id: "pagerduty",
    name: "PagerDuty",
    category: "Engineering",
    auth: "oauth2",
    orgLevel: true,
    reads: "Incidents, responders and follow-up actions.",
    scopesNote: "incidents.read, users.read",
    icon: "logos:pagerduty-icon",
    docsUrl: "https://developer.pagerduty.com/docs/app-oauth-token",
  },
  {
    id: "datadog",
    name: "Datadog",
    category: "Engineering",
    auth: "api_key",
    orgLevel: true,
    reads: "Monitor and incident state for engineering follow-ups.",
    scopesNote: "API key + application key (read)",
    icon: "logos:datadog-icon",
    docsUrl: "https://docs.datadoghq.com/account_management/api-app-keys/",
  },

  // ── Design ───────────────────────────────────────────────────────────────
  {
    id: "figma",
    name: "Figma",
    category: "Design",
    auth: "oauth2",
    reads: "File names, comments and who was asked to review.",
    scopesNote: "files:read",
    icon: "logos:figma",
    docsUrl: "https://www.figma.com/developers/api#oauth2",
  },
  {
    id: "miro",
    name: "Miro",
    category: "Design",
    auth: "oauth2",
    orgLevel: true,
    reads: "Board names and sticky-note text from allowlisted boards.",
    scopesNote: "boards:read",
    icon: "logos:miro-icon",
    docsUrl: "https://developers.miro.com/docs/getting-started-with-oauth",
  },

  // ── People ───────────────────────────────────────────────────────────────
  {
    id: "greenhouse",
    name: "Greenhouse",
    category: "People",
    auth: "api_key",
    orgLevel: true,
    reads: "Interview scorecard owners and hiring-stage follow-ups.",
    scopesNote: "Harvest API key (read)",
    icon: "thesvg-color:greenhouse",
    docsUrl: "https://developers.greenhouse.io/harvest.html",
  },
  {
    id: "gusto",
    name: "Gusto",
    category: "People",
    auth: "oauth2",
    orgLevel: true,
    reads: "Employee directory and time-off windows, so nudges respect absence.",
    scopesNote: "employees:read, time_off:read",
    icon: "logos:gusto",
    docsUrl: "https://docs.gusto.com/app-integrations/docs/authentication",
  },
  {
    id: "personio",
    name: "Personio",
    category: "People",
    auth: "api_key",
    orgLevel: true,
    reads: "Employee directory and absence calendar.",
    scopesNote: "client credentials (read)",
    icon: "thesvg-color:personio",
    docsUrl: "https://developer.personio.de/docs/getting-started-with-the-personio-api",
  },

  // ── Finance ──────────────────────────────────────────────────────────────
  {
    id: "stripe",
    name: "Stripe",
    category: "Finance",
    auth: "api_key",
    orgLevel: true,
    reads: "Invoice and subscription state for client-facing commitments.",
    scopesNote: "restricted key, read-only",
    icon: "logos:stripe",
    docsUrl: "https://docs.stripe.com/keys#limit-access",
  },
  {
    id: "quickbooks",
    name: "QuickBooks",
    category: "Finance",
    auth: "oauth2",
    orgLevel: true,
    reads: "Invoice status and due dates.",
    scopesNote: "com.intuit.quickbooks.accounting (read)",
    icon: "thesvg-color:quickbooks",
    docsUrl: "https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization",
  },
  {
    id: "xero",
    name: "Xero",
    category: "Finance",
    auth: "oauth2",
    orgLevel: true,
    reads: "Invoice status and due dates.",
    scopesNote: "accounting.transactions.read",
    icon: "logos:xero",
    docsUrl: "https://developer.xero.com/documentation/guides/oauth2/auth-flow/",
  },
  {
    id: "shopify",
    name: "Shopify",
    category: "Finance",
    auth: "oauth2",
    orgLevel: true,
    reads: "Order and fulfilment state for operational commitments.",
    scopesNote: "read_orders, read_products",
    icon: "logos:shopify",
    docsUrl: "https://shopify.dev/docs/apps/auth/oauth",
  },

  // ── Marketing & forms ────────────────────────────────────────────────────
  {
    id: "mailchimp",
    name: "Mailchimp",
    category: "Marketing & forms",
    auth: "oauth2",
    orgLevel: true,
    reads: "Campaign schedules and owners.",
    scopesNote: "read-only account access",
    icon: "logos:mailchimp-icon",
    docsUrl: "https://mailchimp.com/developer/marketing/guides/access-user-data-oauth-2/",
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "Marketing & forms",
    auth: "api_key",
    orgLevel: true,
    reads: "Scheduled sends and suppression events.",
    scopesNote: "read-only API key",
    icon: "logos:sendgrid-icon",
    docsUrl: "https://www.twilio.com/docs/sendgrid/api-reference",
  },
  {
    id: "typeform",
    name: "Typeform",
    category: "Marketing & forms",
    auth: "oauth2",
    orgLevel: true,
    reads: "Form responses that carry commitments or check-in answers.",
    scopesNote: "forms:read, responses:read",
    icon: "logos:typeform-icon",
    docsUrl: "https://www.typeform.com/developers/get-started/scopes/",
  },
  {
    id: "google_forms",
    name: "Google Forms",
    category: "Marketing & forms",
    auth: "oauth2",
    reads: "Form responses used for check-ins and surveys.",
    scopesNote: "forms.responses.readonly",
    icon: "thesvg-color:google-forms",
    docsUrl: "https://developers.google.com/forms/api/guides/authorize",
  },

  // ── Analytics ────────────────────────────────────────────────────────────
  {
    id: "google_analytics",
    name: "Google Analytics",
    category: "Analytics",
    auth: "oauth2",
    orgLevel: true,
    reads: "Reporting metrics referenced by project goals.",
    scopesNote: "analytics.readonly",
    icon: "logos:google-analytics",
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries",
  },
  {
    id: "mixpanel",
    name: "Mixpanel",
    category: "Analytics",
    auth: "api_key",
    orgLevel: true,
    reads: "Saved report values referenced by project goals.",
    scopesNote: "service account (read)",
    icon: "thesvg-color:mixpanel",
    docsUrl: "https://developer.mixpanel.com/reference/service-accounts",
  },
  {
    id: "amplitude",
    name: "Amplitude",
    category: "Analytics",
    auth: "api_key",
    orgLevel: true,
    reads: "Chart values referenced by project goals.",
    scopesNote: "API key + secret key (read)",
    icon: "logos:amplitude-icon",
    docsUrl: "https://www.docs.developers.amplitude.com/analytics/apis/dashboard-rest-api/",
  },
  {
    id: "segment",
    name: "Segment",
    category: "Analytics",
    auth: "api_key",
    orgLevel: true,
    reads: "Source and destination health for data commitments.",
    scopesNote: "Public API token (read)",
    icon: "logos:segment-icon",
    docsUrl: "https://docs.segmentapis.com/tag/Getting-Started",
  },

  // ── Identity ─────────────────────────────────────────────────────────────
  {
    id: "okta",
    name: "Okta",
    category: "Identity",
    auth: "oauth2",
    orgLevel: true,
    reads: "Directory users and groups, to keep the org chart current.",
    scopesNote: "okta.users.read, okta.groups.read",
    icon: "logos:okta-icon",
    docsUrl: "https://developer.okta.com/docs/guides/implement-oauth-for-okta/",
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "Identity",
    auth: "oauth2",
    orgLevel: true,
    reads: "Directory users and roles.",
    scopesNote: "read:users, read:roles",
    icon: "thesvg-color:auth0",
    docsUrl: "https://auth0.com/docs/get-started/authentication-and-authorization-flow",
  },
  {
    id: "workos",
    name: "WorkOS",
    category: "Identity",
    auth: "api_key",
    orgLevel: true,
    reads: "SSO profiles and directory sync events.",
    scopesNote: "API key + client ID",
    icon: "logos:workos-icon",
    docsUrl: "https://workos.com/docs/sso/quick-start",
  },

  // ── Automation ───────────────────────────────────────────────────────────
  {
    id: "zapier",
    name: "Zapier",
    category: "Automation",
    auth: "webhook",
    orgLevel: true,
    reads: "Whatever a Zap posts to the workspace's signed endpoint.",
    scopesNote: "signed inbound webhook",
    icon: "logos:zapier-icon",
    docsUrl: "https://platform.zapier.com/build/webhook-trigger",
  },
  {
    id: "make",
    name: "Make",
    category: "Automation",
    auth: "webhook",
    orgLevel: true,
    reads: "Whatever a scenario posts to the workspace's signed endpoint.",
    scopesNote: "signed inbound webhook",
    icon: "thesvg-color:make",
    docsUrl: "https://www.make.com/en/help/tools/webhooks",
  },
  {
    id: "n8n",
    name: "n8n",
    category: "Automation",
    auth: "webhook",
    orgLevel: true,
    reads: "Whatever a workflow posts to the workspace's signed endpoint.",
    scopesNote: "signed inbound webhook",
    icon: "logos:n8n-icon",
    docsUrl: "https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.webhook/",
  },
];

export const PROVIDERS_BY_ID: Record<ConnectionProvider, ProviderMeta> =
  Object.fromEntries(PROVIDERS.map((p) => [p.id, p])) as Record<
    ConnectionProvider,
    ProviderMeta
  >;

export function providerMeta(id: string): ProviderMeta | undefined {
  return PROVIDERS_BY_ID[id as ConnectionProvider];
}

export function providerName(id: string): string {
  return providerMeta(id)?.name ?? id;
}

/** Categories that actually have entries, in display order. */
export function activeCategories(metas: ProviderMeta[] = PROVIDERS): ProviderCategory[] {
  const present = new Set(metas.map((m) => m.category));
  return PROVIDER_CATEGORIES.filter((c) => present.has(c));
}

/** Short list offered during onboarding. */
export const CORE_PROVIDERS: ProviderMeta[] = PROVIDERS.filter((p) => p.core);
