// GENERATED by scripts/gen/edge-providers.mjs — do not edit.
// Source of truth: apps/api/src/lib/providerRegistry.ts
// Regenerate with: node scripts/gen/edge-providers.mjs

export interface EdgeConnector {
  id: string;
  name: string;
  orgLevel: boolean;
  clientIdSecret: string;
  clientSecretSecret: string;
  instanceSecret: string | null;
  featureFlag: string | null;
  authorizeUrl: string;
  tokenUrl: string;
  scopes: string[];
  clientAuth: "body" | "basic";
  pkce: boolean;
  authorizeParams: Record<string, string>;
  jsonAccept: boolean;
  identityUrl: string | null;
  identityPath: string[] | null;
  identityFromToken: string[] | null;
}

export const EDGE_CONNECTORS: Record<string, EdgeConnector> = {
  "gmail": {
    "id": "gmail",
    "name": "Gmail",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/gmail.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "outlook": {
    "id": "outlook",
    "name": "Outlook",
    "orgLevel": false,
    "clientIdSecret": "MICROSOFT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MICROSOFT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
    "tokenUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
    "scopes": [
      "offline_access",
      "User.Read",
      "Mail.Read"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "response_mode": "query"
    },
    "jsonAccept": false,
    "identityUrl": "https://graph.microsoft.com/v1.0/me",
    "identityPath": [
      "mail"
    ],
    "identityFromToken": null
  },
  "front": {
    "id": "front",
    "name": "Front",
    "orgLevel": true,
    "clientIdSecret": "FRONT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "FRONT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://app.frontapp.com/oauth/authorize",
    "tokenUrl": "https://app.frontapp.com/oauth/token",
    "scopes": [],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api2.frontapp.com/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_calendar": {
    "id": "google_calendar",
    "name": "Google Calendar",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/calendar.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "microsoft_calendar": {
    "id": "microsoft_calendar",
    "name": "Microsoft Calendar",
    "orgLevel": false,
    "clientIdSecret": "MICROSOFT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MICROSOFT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
    "tokenUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
    "scopes": [
      "offline_access",
      "User.Read",
      "Calendars.Read"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "response_mode": "query"
    },
    "jsonAccept": false,
    "identityUrl": "https://graph.microsoft.com/v1.0/me",
    "identityPath": [
      "mail"
    ],
    "identityFromToken": null
  },
  "calendly": {
    "id": "calendly",
    "name": "Calendly",
    "orgLevel": false,
    "clientIdSecret": "CALENDLY_OAUTH_CLIENT_ID",
    "clientSecretSecret": "CALENDLY_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://auth.calendly.com/oauth/authorize",
    "tokenUrl": "https://auth.calendly.com/oauth/token",
    "scopes": [],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.calendly.com/users/me",
    "identityPath": [
      "resource",
      "email"
    ],
    "identityFromToken": null
  },
  "zoom": {
    "id": "zoom",
    "name": "Zoom",
    "orgLevel": false,
    "clientIdSecret": "ZOOM_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ZOOM_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://zoom.us/oauth/authorize",
    "tokenUrl": "https://zoom.us/oauth/token",
    "scopes": [
      "meeting:read",
      "recording:read",
      "user:read"
    ],
    "clientAuth": "basic",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.zoom.us/v2/users/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_meet": {
    "id": "google_meet",
    "name": "Google Meet",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/meetings.space.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "webex": {
    "id": "webex",
    "name": "Webex",
    "orgLevel": false,
    "clientIdSecret": "WEBEX_OAUTH_CLIENT_ID",
    "clientSecretSecret": "WEBEX_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://webexapis.com/v1/authorize",
    "tokenUrl": "https://webexapis.com/v1/access_token",
    "scopes": [
      "spark:kms",
      "meeting:schedules_read",
      "meeting:recordings_read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://webexapis.com/v1/people/me",
    "identityPath": [
      "emails",
      "0"
    ],
    "identityFromToken": null
  },
  "slack": {
    "id": "slack",
    "name": "Slack",
    "orgLevel": true,
    "clientIdSecret": "SLACK_OAUTH_CLIENT_ID",
    "clientSecretSecret": "SLACK_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://slack.com/oauth/v2/authorize",
    "tokenUrl": "https://slack.com/api/oauth.v2.access",
    "scopes": [
      "channels:history",
      "channels:read",
      "users:read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": [
      "team",
      "name"
    ]
  },
  "teams": {
    "id": "teams",
    "name": "Microsoft Teams",
    "orgLevel": true,
    "clientIdSecret": "MICROSOFT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MICROSOFT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
    "tokenUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
    "scopes": [
      "offline_access",
      "User.Read",
      "ChannelMessage.Read.All",
      "Team.ReadBasic.All"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "response_mode": "query"
    },
    "jsonAccept": false,
    "identityUrl": "https://graph.microsoft.com/v1.0/me",
    "identityPath": [
      "mail"
    ],
    "identityFromToken": null
  },
  "google_chat": {
    "id": "google_chat",
    "name": "Google Chat",
    "orgLevel": true,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/chat.spaces.readonly",
      "https://www.googleapis.com/auth/chat.messages.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "discord": {
    "id": "discord",
    "name": "Discord",
    "orgLevel": true,
    "clientIdSecret": "DISCORD_OAUTH_CLIENT_ID",
    "clientSecretSecret": "DISCORD_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://discord.com/oauth2/authorize",
    "tokenUrl": "https://discord.com/api/oauth2/token",
    "scopes": [
      "identify",
      "guilds",
      "messages.read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://discord.com/api/users/@me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "jira": {
    "id": "jira",
    "name": "Jira",
    "orgLevel": true,
    "clientIdSecret": "ATLASSIAN_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ATLASSIAN_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://auth.atlassian.com/authorize",
    "tokenUrl": "https://auth.atlassian.com/oauth/token",
    "scopes": [
      "read:jira-work",
      "read:jira-user",
      "offline_access"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {
      "audience": "api.atlassian.com",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://api.atlassian.com/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "asana": {
    "id": "asana",
    "name": "Asana",
    "orgLevel": true,
    "clientIdSecret": "ASANA_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ASANA_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://app.asana.com/-/oauth_authorize",
    "tokenUrl": "https://app.asana.com/-/oauth_token",
    "scopes": [
      "openid",
      "email",
      "tasks:read",
      "projects:read",
      "users:read"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://app.asana.com/api/1.0/users/me",
    "identityPath": [
      "data",
      "email"
    ],
    "identityFromToken": null
  },
  "linear": {
    "id": "linear",
    "name": "Linear",
    "orgLevel": true,
    "clientIdSecret": "LINEAR_OAUTH_CLIENT_ID",
    "clientSecretSecret": "LINEAR_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://linear.app/oauth/authorize",
    "tokenUrl": "https://api.linear.app/oauth/token",
    "scopes": [
      "read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "monday": {
    "id": "monday",
    "name": "monday.com",
    "orgLevel": true,
    "clientIdSecret": "MONDAY_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MONDAY_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://auth.monday.com/oauth2/authorize",
    "tokenUrl": "https://auth.monday.com/oauth2/token",
    "scopes": [
      "boards:read",
      "users:read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "clickup": {
    "id": "clickup",
    "name": "ClickUp",
    "orgLevel": true,
    "clientIdSecret": "CLICKUP_OAUTH_CLIENT_ID",
    "clientSecretSecret": "CLICKUP_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://app.clickup.com/api",
    "tokenUrl": "https://api.clickup.com/api/v2/oauth/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.clickup.com/api/v2/user",
    "identityPath": [
      "user",
      "email"
    ],
    "identityFromToken": null
  },
  "basecamp": {
    "id": "basecamp",
    "name": "Basecamp",
    "orgLevel": true,
    "clientIdSecret": "BASECAMP_OAUTH_CLIENT_ID",
    "clientSecretSecret": "BASECAMP_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://launchpad.37signals.com/authorization/new",
    "tokenUrl": "https://launchpad.37signals.com/authorization/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {
      "type": "web_server"
    },
    "jsonAccept": false,
    "identityUrl": "https://launchpad.37signals.com/authorization.json",
    "identityPath": [
      "identity",
      "email_address"
    ],
    "identityFromToken": null
  },
  "todoist": {
    "id": "todoist",
    "name": "Todoist",
    "orgLevel": false,
    "clientIdSecret": "TODOIST_OAUTH_CLIENT_ID",
    "clientSecretSecret": "TODOIST_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://todoist.com/oauth/authorize",
    "tokenUrl": "https://todoist.com/oauth/access_token",
    "scopes": [
      "data:read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "notion": {
    "id": "notion",
    "name": "Notion",
    "orgLevel": true,
    "clientIdSecret": "NOTION_OAUTH_CLIENT_ID",
    "clientSecretSecret": "NOTION_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://api.notion.com/v1/oauth/authorize",
    "tokenUrl": "https://api.notion.com/v1/oauth/token",
    "scopes": [],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {
      "owner": "user"
    },
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": [
      "workspace_name"
    ]
  },
  "confluence": {
    "id": "confluence",
    "name": "Confluence",
    "orgLevel": true,
    "clientIdSecret": "ATLASSIAN_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ATLASSIAN_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://auth.atlassian.com/authorize",
    "tokenUrl": "https://auth.atlassian.com/oauth/token",
    "scopes": [
      "read:confluence-content.summary",
      "read:confluence-space.summary",
      "offline_access"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {
      "audience": "api.atlassian.com",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://api.atlassian.com/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_docs": {
    "id": "google_docs",
    "name": "Google Docs",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/documents.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_sheets": {
    "id": "google_sheets",
    "name": "Google Sheets",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/spreadsheets.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "airtable": {
    "id": "airtable",
    "name": "Airtable",
    "orgLevel": true,
    "clientIdSecret": "AIRTABLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "AIRTABLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://airtable.com/oauth2/v1/authorize",
    "tokenUrl": "https://airtable.com/oauth2/v1/token",
    "scopes": [
      "data.records:read",
      "schema.bases:read",
      "user.email:read"
    ],
    "clientAuth": "basic",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.airtable.com/v0/meta/whoami",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_drive": {
    "id": "google_drive",
    "name": "Google Drive",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/drive.metadata.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "onedrive": {
    "id": "onedrive",
    "name": "OneDrive",
    "orgLevel": false,
    "clientIdSecret": "MICROSOFT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MICROSOFT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
    "tokenUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
    "scopes": [
      "offline_access",
      "User.Read",
      "Files.Read.All"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "response_mode": "query"
    },
    "jsonAccept": false,
    "identityUrl": "https://graph.microsoft.com/v1.0/me",
    "identityPath": [
      "mail"
    ],
    "identityFromToken": null
  },
  "sharepoint": {
    "id": "sharepoint",
    "name": "SharePoint",
    "orgLevel": true,
    "clientIdSecret": "MICROSOFT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MICROSOFT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/authorize",
    "tokenUrl": "https://login.microsoftonline.com/{tenant}/oauth2/v2.0/token",
    "scopes": [
      "offline_access",
      "User.Read",
      "Sites.Read.All"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "response_mode": "query"
    },
    "jsonAccept": false,
    "identityUrl": "https://graph.microsoft.com/v1.0/me",
    "identityPath": [
      "mail"
    ],
    "identityFromToken": null
  },
  "dropbox": {
    "id": "dropbox",
    "name": "Dropbox",
    "orgLevel": false,
    "clientIdSecret": "DROPBOX_OAUTH_CLIENT_ID",
    "clientSecretSecret": "DROPBOX_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://www.dropbox.com/oauth2/authorize",
    "tokenUrl": "https://api.dropboxapi.com/oauth2/token",
    "scopes": [
      "files.metadata.read",
      "account_info.read"
    ],
    "clientAuth": "basic",
    "pkce": true,
    "authorizeParams": {
      "token_access_type": "offline"
    },
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "box": {
    "id": "box",
    "name": "Box",
    "orgLevel": false,
    "clientIdSecret": "BOX_OAUTH_CLIENT_ID",
    "clientSecretSecret": "BOX_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://account.box.com/api/oauth2/authorize",
    "tokenUrl": "https://api.box.com/oauth2/token",
    "scopes": [
      "root_readonly"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.box.com/2.0/users/me",
    "identityPath": [
      "login"
    ],
    "identityFromToken": null
  },
  "hubspot": {
    "id": "hubspot",
    "name": "HubSpot",
    "orgLevel": true,
    "clientIdSecret": "HUBSPOT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "HUBSPOT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://app.hubspot.com/oauth/authorize",
    "tokenUrl": "https://api.hubapi.com/oauth/v1/token",
    "scopes": [
      "oauth",
      "crm.objects.deals.read",
      "crm.objects.contacts.read",
      "crm.objects.companies.read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "salesforce": {
    "id": "salesforce",
    "name": "Salesforce",
    "orgLevel": true,
    "clientIdSecret": "SALESFORCE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "SALESFORCE_OAUTH_CLIENT_SECRET",
    "instanceSecret": "SALESFORCE_LOGIN_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/services/oauth2/authorize",
    "tokenUrl": "https://{instance}/services/oauth2/token",
    "scopes": [
      "api",
      "refresh_token",
      "openid",
      "email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://{instance}/services/oauth2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "pipedrive": {
    "id": "pipedrive",
    "name": "Pipedrive",
    "orgLevel": true,
    "clientIdSecret": "PIPEDRIVE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "PIPEDRIVE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://oauth.pipedrive.com/oauth/authorize",
    "tokenUrl": "https://oauth.pipedrive.com/oauth/token",
    "scopes": [],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.pipedrive.com/v1/users/me",
    "identityPath": [
      "data",
      "email"
    ],
    "identityFromToken": null
  },
  "zoho_crm": {
    "id": "zoho_crm",
    "name": "Zoho CRM",
    "orgLevel": true,
    "clientIdSecret": "ZOHO_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ZOHO_OAUTH_CLIENT_SECRET",
    "instanceSecret": "ZOHO_ACCOUNTS_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/oauth/v2/auth",
    "tokenUrl": "https://{instance}/oauth/v2/token",
    "scopes": [
      "ZohoCRM.modules.READ",
      "ZohoCRM.users.READ"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "docusign": {
    "id": "docusign",
    "name": "DocuSign",
    "orgLevel": true,
    "clientIdSecret": "DOCUSIGN_OAUTH_CLIENT_ID",
    "clientSecretSecret": "DOCUSIGN_OAUTH_CLIENT_SECRET",
    "instanceSecret": "DOCUSIGN_AUTH_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/oauth/auth",
    "tokenUrl": "https://{instance}/oauth/token",
    "scopes": [
      "signature",
      "extended"
    ],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://{instance}/oauth/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "zendesk": {
    "id": "zendesk",
    "name": "Zendesk",
    "orgLevel": true,
    "clientIdSecret": "ZENDESK_OAUTH_CLIENT_ID",
    "clientSecretSecret": "ZENDESK_OAUTH_CLIENT_SECRET",
    "instanceSecret": "ZENDESK_SUBDOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}.zendesk.com/oauth/authorizations/new",
    "tokenUrl": "https://{instance}.zendesk.com/oauth/tokens",
    "scopes": [
      "read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://{instance}.zendesk.com/api/v2/users/me",
    "identityPath": [
      "user",
      "email"
    ],
    "identityFromToken": null
  },
  "intercom": {
    "id": "intercom",
    "name": "Intercom",
    "orgLevel": true,
    "clientIdSecret": "INTERCOM_OAUTH_CLIENT_ID",
    "clientSecretSecret": "INTERCOM_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://app.intercom.com/oauth",
    "tokenUrl": "https://api.intercom.io/auth/eagle/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.intercom.io/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "helpscout": {
    "id": "helpscout",
    "name": "Help Scout",
    "orgLevel": true,
    "clientIdSecret": "HELPSCOUT_OAUTH_CLIENT_ID",
    "clientSecretSecret": "HELPSCOUT_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://secure.helpscout.net/authentication/authorizeClientApplication",
    "tokenUrl": "https://api.helpscout.net/v2/oauth2/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.helpscout.net/v2/users/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "github": {
    "id": "github",
    "name": "GitHub",
    "orgLevel": true,
    "clientIdSecret": "GITHUB_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GITHUB_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://github.com/login/oauth/authorize",
    "tokenUrl": "https://github.com/login/oauth/access_token",
    "scopes": [
      "read:org",
      "read:user",
      "repo:status"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": true,
    "identityUrl": "https://api.github.com/user",
    "identityPath": [
      "login"
    ],
    "identityFromToken": null
  },
  "gitlab": {
    "id": "gitlab",
    "name": "GitLab",
    "orgLevel": true,
    "clientIdSecret": "GITLAB_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GITLAB_OAUTH_CLIENT_SECRET",
    "instanceSecret": "GITLAB_BASE_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/oauth/authorize",
    "tokenUrl": "https://{instance}/oauth/token",
    "scopes": [
      "read_api",
      "read_user"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://{instance}/api/v4/user",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "bitbucket": {
    "id": "bitbucket",
    "name": "Bitbucket",
    "orgLevel": true,
    "clientIdSecret": "BITBUCKET_OAUTH_CLIENT_ID",
    "clientSecretSecret": "BITBUCKET_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://bitbucket.org/site/oauth2/authorize",
    "tokenUrl": "https://bitbucket.org/site/oauth2/access_token",
    "scopes": [],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.bitbucket.org/2.0/user",
    "identityPath": [
      "username"
    ],
    "identityFromToken": null
  },
  "pagerduty": {
    "id": "pagerduty",
    "name": "PagerDuty",
    "orgLevel": true,
    "clientIdSecret": "PAGERDUTY_OAUTH_CLIENT_ID",
    "clientSecretSecret": "PAGERDUTY_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://identity.pagerduty.com/oauth/authorize",
    "tokenUrl": "https://identity.pagerduty.com/oauth/token",
    "scopes": [
      "incidents.read",
      "users.read"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.pagerduty.com/users/me",
    "identityPath": [
      "user",
      "email"
    ],
    "identityFromToken": null
  },
  "figma": {
    "id": "figma",
    "name": "Figma",
    "orgLevel": false,
    "clientIdSecret": "FIGMA_OAUTH_CLIENT_ID",
    "clientSecretSecret": "FIGMA_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://www.figma.com/oauth",
    "tokenUrl": "https://api.figma.com/v1/oauth/token",
    "scopes": [
      "files:read"
    ],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.figma.com/v1/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "miro": {
    "id": "miro",
    "name": "Miro",
    "orgLevel": true,
    "clientIdSecret": "MIRO_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MIRO_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://miro.com/oauth/authorize",
    "tokenUrl": "https://api.miro.com/v1/oauth/token",
    "scopes": [
      "boards:read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "gusto": {
    "id": "gusto",
    "name": "Gusto",
    "orgLevel": true,
    "clientIdSecret": "GUSTO_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GUSTO_OAUTH_CLIENT_SECRET",
    "instanceSecret": "GUSTO_API_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/oauth/authorize",
    "tokenUrl": "https://{instance}/oauth/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "quickbooks": {
    "id": "quickbooks",
    "name": "QuickBooks",
    "orgLevel": true,
    "clientIdSecret": "QUICKBOOKS_OAUTH_CLIENT_ID",
    "clientSecretSecret": "QUICKBOOKS_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://appcenter.intuit.com/connect/oauth2",
    "tokenUrl": "https://oauth.platform.intuit.com/oauth2/v1/tokens/bearer",
    "scopes": [
      "com.intuit.quickbooks.accounting",
      "openid",
      "email"
    ],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://accounts.platform.intuit.com/v1/openid_connect/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "xero": {
    "id": "xero",
    "name": "Xero",
    "orgLevel": true,
    "clientIdSecret": "XERO_OAUTH_CLIENT_ID",
    "clientSecretSecret": "XERO_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.xero.com/identity/connect/authorize",
    "tokenUrl": "https://identity.xero.com/connect/token",
    "scopes": [
      "openid",
      "email",
      "offline_access",
      "accounting.transactions.read"
    ],
    "clientAuth": "basic",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "shopify": {
    "id": "shopify",
    "name": "Shopify",
    "orgLevel": true,
    "clientIdSecret": "SHOPIFY_OAUTH_CLIENT_ID",
    "clientSecretSecret": "SHOPIFY_OAUTH_CLIENT_SECRET",
    "instanceSecret": "SHOPIFY_SHOP_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/admin/oauth/authorize",
    "tokenUrl": "https://{instance}/admin/oauth/access_token",
    "scopes": [
      "read_orders",
      "read_products"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": null,
    "identityPath": null,
    "identityFromToken": null
  },
  "mailchimp": {
    "id": "mailchimp",
    "name": "Mailchimp",
    "orgLevel": true,
    "clientIdSecret": "MAILCHIMP_OAUTH_CLIENT_ID",
    "clientSecretSecret": "MAILCHIMP_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://login.mailchimp.com/oauth2/authorize",
    "tokenUrl": "https://login.mailchimp.com/oauth2/token",
    "scopes": [],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://login.mailchimp.com/oauth2/metadata",
    "identityPath": [
      "login",
      "email"
    ],
    "identityFromToken": null
  },
  "typeform": {
    "id": "typeform",
    "name": "Typeform",
    "orgLevel": true,
    "clientIdSecret": "TYPEFORM_OAUTH_CLIENT_ID",
    "clientSecretSecret": "TYPEFORM_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://api.typeform.com/oauth/authorize",
    "tokenUrl": "https://api.typeform.com/oauth/token",
    "scopes": [
      "forms:read",
      "responses:read",
      "accounts:read"
    ],
    "clientAuth": "body",
    "pkce": false,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://api.typeform.com/me",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_forms": {
    "id": "google_forms",
    "name": "Google Forms",
    "orgLevel": false,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/forms.responses.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "google_analytics": {
    "id": "google_analytics",
    "name": "Google Analytics",
    "orgLevel": true,
    "clientIdSecret": "GOOGLE_OAUTH_CLIENT_ID",
    "clientSecretSecret": "GOOGLE_OAUTH_CLIENT_SECRET",
    "instanceSecret": null,
    "featureFlag": null,
    "authorizeUrl": "https://accounts.google.com/o/oauth2/v2/auth",
    "tokenUrl": "https://oauth2.googleapis.com/token",
    "scopes": [
      "https://www.googleapis.com/auth/analytics.readonly",
      "openid",
      "https://www.googleapis.com/auth/userinfo.email"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "access_type": "offline",
      "prompt": "consent"
    },
    "jsonAccept": false,
    "identityUrl": "https://www.googleapis.com/oauth2/v2/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "okta": {
    "id": "okta",
    "name": "Okta",
    "orgLevel": true,
    "clientIdSecret": "OKTA_OAUTH_CLIENT_ID",
    "clientSecretSecret": "OKTA_OAUTH_CLIENT_SECRET",
    "instanceSecret": "OKTA_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/oauth2/v1/authorize",
    "tokenUrl": "https://{instance}/oauth2/v1/token",
    "scopes": [
      "openid",
      "email",
      "okta.users.read",
      "okta.groups.read"
    ],
    "clientAuth": "basic",
    "pkce": true,
    "authorizeParams": {},
    "jsonAccept": false,
    "identityUrl": "https://{instance}/oauth2/v1/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
  "auth0": {
    "id": "auth0",
    "name": "Auth0",
    "orgLevel": true,
    "clientIdSecret": "AUTH0_OAUTH_CLIENT_ID",
    "clientSecretSecret": "AUTH0_OAUTH_CLIENT_SECRET",
    "instanceSecret": "AUTH0_DOMAIN",
    "featureFlag": null,
    "authorizeUrl": "https://{instance}/authorize",
    "tokenUrl": "https://{instance}/oauth/token",
    "scopes": [
      "openid",
      "email",
      "read:users",
      "read:roles",
      "offline_access"
    ],
    "clientAuth": "body",
    "pkce": true,
    "authorizeParams": {
      "audience": "https://{instance}/api/v2/"
    },
    "jsonAccept": false,
    "identityUrl": "https://{instance}/userinfo",
    "identityPath": [
      "email"
    ],
    "identityFromToken": null
  },
};

export const EDGE_PROVIDER_IDS = Object.keys(EDGE_CONNECTORS);
